name: Build and publish boofstream for download
run-name: Build and publish boofstream for download
on:
  push:
    tags:
      - "v*"
jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # --- Setup ---
      - name: Install node
        uses: actions/setup-node@v4
      - name: Check out repository code
        uses: actions/checkout@v4
    # --- boofstream-common ---
      - name: Install boofstream-common dependencies
        working-directory: ./boofstream-common
        run: npm i --save-dev
      - name: Build boofstream-common
        working-directory: ./boofstream-common
        run: npx tsc
    # --- boofstream-manager ---
      - name: Install boofstream-manager dependencies
        working-directory: ./boofstream-manager
        run: npm i --save-dev
      - name: Build boofstream-manager
        working-directory: ./boofstream-manager
        run: npm run build
    # --- boofstream ---
      - name: Remove isReleaseArtifact.ts
        run: rm boofstream/isReleaseArtifact.ts
      - name: Write isReleaseArtifact.ts
        run: echo "export default true" > isReleaseArtifact.ts
      - name: Check marked as release artifact
        run: cat boofstream/isReleaseArtifact.ts
      - name: Install boofstream dependencies
        working-directory: ./boofstream
        run: npm i --save-dev
      - name: Build boofstream
        working-directory: ./boofstream
        run: npx tsc
      - name: Install yao-pkg
        run: npm i -g @yao-pkg/pkg
    # --- release dir ---
      - name: Make release dir
        run: mkdir release
      - name: Copy assets
        run: cp -r boofstream/assets release/assets
      - name: Make dist dir
        run: mkdir release/dist
      - name: Copy UI
        run: cp -r boofstream-manager/out release/dist/ui
      # - name: Clone TournamentStreamHelper
      #   run: git clone https://github.com/joaorb64/TournamentStreamHelper
      # - name: Copy TSH layouts into boofstream
      #   run: cp -r TournamentStreamHelper/layout boofstream/layouts
      # - name: Copy TSH license into layouts
      #   run: cp TournamentStreamHelper/LICENSE boofstream/layouts/LICENSE
    # --- artifacts ---
      - name: Make release artifact (Windows x64)
        run: sh scripts/make-release-artifact.sh win-x64 windows-x64 .exe
    # --- release ---
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.version.outputs.version }}
          artifacts: "boofstream-*.zip"
